### ISSUE TITLE
Support colorful output in short test summary info

### ISSUE THREAD

**Issue by davidak** [wimglenn/pytest-custom-report#5]
Is there a way to set the color of the status?

Right now it's the same color like the text:

![screenshot from 2019-01-31 15-12-09](https://user-images.githubusercontent.com/91113/52059796-078e3780-256b-11e9-8910-179eaed283b0.png)

If not possible right now, it would be great to have support added.

Maybe that could be changed upstream to match the verbose test output?

**Comment by davidak** [comment]
Maybe it is helpful to know that my operating system not fully supports emojis. Not sure how it would look like on Ubuntu for example.

OS: NixOS 18.09.1974.50f41ea2fcf (Jellyfish)
DE: GNOME 3
Terminal: Pantheon Terminal

**Comment by wimglenn** [comment]
Hi @davidak, as with your previous issue, this is something that would need to be addressed in pytest directly. It is pytest code that prints out the terminal summary, not this plugin. 

You could, however, workaround it by putting the colours directly in the report string. For example, a green tick would be `\x1b[32m✔\x1b[0m`. 

So in `pytest.ini` you would have:

```
[pytest]
report_passed_verbose = [32m✔[0m
```

Make sure to put the actual characters, so they don't get escaped twice (I think github maybe screwing up the escapes when rendering here).

Does that help?

**Comment by davidak** [comment]
Yes, that's an acceptable solution!

I actually used such escape sequences before for colored terminal output.

**Comment by davidak** [comment]
With

```
[pytest]
report_passed_verbose = \x1b[32m✔\x1b[0m
```

it just prints the characters:

```
\x1b[32m✔\x1b[0m Check for correct kernel type
```

But with parameters from my script it works:

```
OK_MARK = "\033[92m✔\033[0m"
FAIL_MARK = "\033[91m✘\033[0m"
SKIP_MARK = "\033[93m⏭️\033[0m"

main():
   ...
    print("Running tests")
    pytest.main(["-q", "--tb=short", "-rap", "--report-failed=" + FAIL_MARK, "--report-passed-verbose=" + OK_MARK, "--report-failed-verbose=" + FAIL_MARK, "--report-skipped-verbose=" + SKIP_MARK], plugins=[PytestVariablePlugin()])
```
![screenshot from 2019-02-04 15-16-11](https://user-images.githubusercontent.com/91113/52213606-d75ad780-288f-11e9-9e36-988e5b332a8a.png)

**Comment by wimglenn** [comment]
Escaped twice. This is what I meant when I was saying **Make sure to put the actual characters**, not the escaped characters, to config file. Try again creating the file like this for example:

```
with open('/tmp/pytest.ini', 'w') as f: 
    f.write("[pytest]\n") 
    f.write(f"report_passed_verbose = {OK_MARK}\n") 
    f.write(f"report_failed_verbose = {FAIL_MARK}\n") 
    f.write(f"report_skipped_verbose = {SKIP_MARK}\n")
```
